---
resources:
- name: CVrepo
  type: git
  source:
    uri: https://github.com/PhilipHarries/CV.git
    branch: master

jobs:
- name: html-lint-cv
  public: true
  build-logs-to-retain: 8
  plan:
  - get: CVrepo
    trigger: true
  - task: html-lint
    file: CVrepo/ci/pipelines/html-lint.yml

- name: deploy-cv
  public: true
  build-logs-to-retain: 8
  plan:
  - get: CVrepo
    passed: [html-lint-cv]
    trigger: true
  - task: deploy
    file: CVrepo/ci/pipelines/deploy.yml
